### ISSUE TITLE
Using the deconstruction planner on infinity loaders doesn't completely remove them

### ISSUE THREAD

**Issue by asyagelski** [raiguard/InfinityMode#23]
As per the title, using the deconstruction planner on infinity loaders doesn't completely remove them. See attached images.

Not sure if this applies to other modded items as well.

[Image 1 - "Ghost" infinity loaders](https://i.imgur.com/Zavlm48.png)
[Image 2 - Error it gives when placing something on top](https://i.imgur.com/GTKgI9O.png)

**Comment by raiguard** [comment]
Thanks for the report. That's really strange, since I specifically tested that before releasing the mod...

However, I am no longer supporting Infinity Mode. It is getting replaced by [Editor Extensions](https://github.com/raiguard/Factorio-EditorExtensions) when Factorio 0.18 releases. I'll make sure this is fixed for that mod.

**Comment by asyagelski** [comment]
Sweet, thanks for the quick reply!
